### ISSUE TITLE
logo for DISCORD server dumans-txt

### ISSUE THREAD

**Issue by sebiboga** [sebiboga/humans-txt#32]
logo for DISCORD server dumans-txt

**Comment by micahyoung324** [comment]
Hello! I am intrigued by this project. I assume you already asked for logo permission. Here's my logo images for the discord server. Let me know what you think!

![humanstxt_discord_logo_white](https://github.com/sebiboga/humans-txt/assets/27590321/1db61c1b-243f-421e-9088-658dab570bd0) ![humanstxt_discord_logo_black](https://github.com/sebiboga/humans-txt/assets/27590321/0c48c92f-4e91-4501-a52c-8efa6142e7d7)

**Comment by sebiboga** [comment]
@micahyoung324 did you joined DISCORD server already?
Why are you intrigued? 
I'll go forward and add first logo to the server...

**Comment by sebiboga** [comment]
@micahyoung324 it looks really nice
thank you for your effort
![image](https://github.com/sebiboga/humans-txt/assets/41440889/64b215c4-ca73-40d2-85d4-ecf21dcb3a4a)

**Comment by micahyoung324** [comment]
> @micahyoung324 did you joined DISCORD server already? Why are you intrigued? I'll go forward and add first logo to the server...

Yes I joined. I just forgot to update my server name. You should see same username as here now. 

I just think this project is a neat and nice introduction to humans.txt. Simple but good way to celebrate humanity.

**Comment by sebiboga** [comment]
Thank you.
Indeed. It is.
