### ISSUE TITLE
Long humans.txt pushes input container out of reach.

### ISSUE THREAD

**Issue by micahyoung324** [sebiboga/humans-txt#36]
If you enter a website with long `humans.txt`, it would push input container out of the view and you couldn't scroll it up. This forces users to reload website.

Examples:
- `adultswims.com`
- `medium.com`
- `trello.com`

**Comment by sebiboga** [comment]
indeed. this is an UI issue.
@VACostin can you help me with fixing this from CSS ?

**Comment by arashjafari** [comment]
@sebiboga I can fix it. Do you agree that I should work on it?

**Comment by sebiboga** [comment]
@arashjafari please go ahead. I assigned this bug to you. Happy coding...
