### ISSUE TITLE
change fallback to humanstxt.org for API endpoint

### ISSUE THREAD

**Issue by sebiboga** [sebiboga/humans-txt#43]
API endpoint should have fallback to humanstxt.org

**Comment by arashjafari** [comment]
Can you please provide more information about your request? What exactly do you need assistance with?

**Comment by sebiboga** [comment]
Right now if you don't provide any domain, it will return humans.txt for peviitor.ro
Because the origin project is humanstxt.org, we should make this one the default one.
It's in backend this change to be made.
Folder in repository is called engine.
Code is written in PHP
