### ISSUE TITLE
Low Text / Background Contrast Colors

### ISSUE THREAD

**Issue by micahyoung324** [sebiboga/humans-txt#50]
This is more of personal preference, but I believe white text on dark background, or black text on white background would be better as it is high contrast.

**Comment by sebiboga** [comment]
@arashjafari what do you think?

**Comment by arashjafari** [comment]
It appears that the text is difficult to read, so we should increase the contrast between the background and the text. I can fix this

**Comment by sebiboga** [comment]
@micahyoung324 is it better now?

**Comment by micahyoung324** [comment]
Yeah much better! Thanks!
