### ISSUE TITLE
Improve Logo Readability

### ISSUE THREAD

**Issue by micahyoung324** [sebiboga/humans-txt#51]
I am on 1080 x 1920 screen and this is what the page looks like. It is hard to read first 't' in txt on this screen and we can fix that.

![vivaldi_306](https://github.com/sebiboga/humans-txt/assets/27590321/c9728fb2-c166-4a08-9c1e-02807e47bea0)

**Comment by sebiboga** [comment]
for id logo2 we should update this CSS value
 background-color: rgb(212 223 230 / 82%);

**Comment by sebiboga** [comment]
@arashjafari can you please fix this for us?

**Comment by arashjafari** [comment]
Sure, I will do it

**Comment by sebiboga** [comment]
@micahyoung324 is it better now?

**Comment by micahyoung324** [comment]
Yeah much better! Thanks!
