### ISSUE TITLE
invite people to humans-txt DISCORD community

### ISSUE THREAD

**Issue by sebiboga** [sebiboga/humans-txt#8]
invite people to join DISCORD community

**Comment by mademoiselle-chantal** [comment]
Hello, @sebiboga! I would like to work on this issue.

**Comment by sebiboga** [comment]
@mademoiselle-chantal excellent. Thank you. Let me create the DISCORD server and give you the link.

**Comment by sebiboga** [comment]
@mademoiselle-chantal here is the DISCORD Invitation link:
https://discord.gg/gWjWqeegHY
Feel free to spread the word!

**Comment by sebiboga** [comment]
@mademoiselle-chantal let me know if you need anything else.

**Comment by mademoiselle-chantal** [comment]
> @mademoiselle-chantal let me know if you need anything else.

Alright, so my job is to let people know about Humans-txt and l would like to know if is there a specific number of people l should invite for me to get the work completed and marked for Hackertoberfest.

**Comment by mademoiselle-chantal** [comment]
@sebiboga I'm trying to draft an inspiring message l can post to spread the word about humans-txt. So, l would like to know if you're okay with these as goals of the community:

 🧠 - Explore the limitless potential of human intelligence.
💡 - Share your thoughts, ideas, and experiences in a world dominated by technology.
🤝 -Connect with like-minded individuals who believe in the power of human expression.

**Comment by sebiboga** [comment]
@mademoiselle-chantal I love the message. Thank you very much for your involvement

**Comment by mademoiselle-chantal** [comment]
> > @mademoiselle-chantal let me know if you need anything else.
> 
> Alright, so my job is to let people know about Humans-txt and l would like to know if is there a specific number of people l should invite for me to get the work completed and marked for Hackertoberfest.

Maybe you might have missed this.

**Comment by sebiboga** [comment]
I missed it, you're right.
As many as you can in a window of 1 day. After 1 day you can mark it as done.
@mademoiselle-chantal  Thank you for your help !

**Comment by sebiboga** [comment]
@mademoiselle-chantal now the app is up and running here: 
https://sebiboga.github.io/humans-txt/

you can update in your message that the application is running and now we collect all the domains that you guys are checking if they have a humans.txt file

**Comment by sebiboga** [comment]
thank you @mademoiselle-chantal
